#ifndef FTPRESPONSECODE_H_INCLUDED
#define FTPRESPONSECODE_H_INCLUDED


#define FTP_SUCCESS 200  //成功
#define FTP_SERVICE_READY 220 //服务器就绪
#define FTP_LOGIN_SUCCESS 230 //登录因特网服务器
#define FTP_FILE_ACTION_COMPLETE 250 //文件行为完成
#define FTP_FILE_CREATED 257 //文件创建成功
#define FTP_PASSWORD_REQUIREd 331 //要求密码
#define FTP_LOGIN_PASSWORD_INCORRECT 530 //用户密码错误


#endif // FTPRESPONSECODE_H_INCLUDED
